# Generated by Django 2.0 on 2017-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=10, verbose_name='大洲')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('time', models.DateField(verbose_name='发生时间')),
                ('dynasty', models.CharField(max_length=100, verbose_name='朝代/时代')),
                ('person', models.CharField(max_length=100, verbose_name='人物')),
                ('address', models.CharField(max_length=100, verbose_name='地点')),
                ('abstract', models.CharField(max_length=100, verbose_name='事件简介')),
                ('detailed', models.TextField(verbose_name='事件详细')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
