# Generated by Django 2.0 on 2017-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytimeline',
            name='BC',
            field=models.BooleanField(default=1, verbose_name='公元前'),
            preserve_default=False,
        ),
    ]
