# Generated by Django 2.0 on 2017-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20171212_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytimeline',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='continent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='大洲'),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='dynasty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='朝代/时代'),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='人物'),
        ),
    ]
